### ISSUE TITLE
Updating docker

### ISSUE THREAD

**Issue by askoeho** [tillsteinbach/VWsFriend#114]
I just updated to the latest dockers images available at the moment (0.10.1). I do not remember the exact old version I had but it was a pretty recent one from the end of last week.

I get the following error message when I try to launch the updated images.

```
vwsfriend_1   | 2021-12-06T21:11:27+0000:INFO:agent_connector:It looks like you have an existing database will check if an upgrade is necessary
vwsfriend_1   | 2021-12-06T21:11:27+0000:INFO:migration:Context impl PostgresqlImpl.
vwsfriend_1   | 2021-12-06T21:11:27+0000:INFO:migration:Will assume transactional DDL.
vwsfriend_1   | 2021-12-06T21:11:27+0000:INFO:migration:Running upgrade f6785099280a -> 91dac376210b, New enum values
postgresdb_1  | 2021-12-06 21:11:27.572 UTC [30] ERROR:  enum label "CHARGE_PURPOSE_REACHED_NOT_CONSERVATION_CHARGING" already exists
postgresdb_1  | 2021-12-06 21:11:27.572 UTC [30] STATEMENT:  ALTER TYPE chargingstate ADD VALUE 'CHARGE_PURPOSE_REACHED_NOT_CONSERVATION_CHARGING'
```

Please let me know if you need the long traceback error message or other logs.

**Comment by tillsteinbach** [comment]
Ah damn! There was a problem with the 0.10.0 and I thought I was fast enough to release the 0.10.1 so that it does not affect people.

There is an easy way to fix that and a difficult one. How important is it for you to not loose the data you recorded already?

If you can afford loosing it you can delete the database with
docker-compose down -v

For a solution where the data is not lost I have to investigate a bit more.

**Comment by askoeho** [comment]
I don't have that much history on the database so I'm good to go with loosing data. I just setup everything back up again from scratch. Thanks!

**Comment by tillsteinbach** [comment]
Sorry for the inconvenience, I need to take care better in the future so that this does not happen again.
