### ISSUE TITLE
docker-compose issue

### ISSUE THREAD

**Issue by al-bear** [tillsteinbach/VWsFriend#591]
Hallo zusammen,

ich bekomme beim docker-compose folgenden Fehler.

raspberry pi 4
Debian GNU/Linux 11 (bullseye)

sudo docker-compose --env-file ./myconfig.env up
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

Danke für die Unterstützung!
Gruß
Alex

PS: Sehr cooles Projekt. Vielen Dank für die Arbeit.

**Comment by claesto** [comment]
I found this: [Removed SSL version (ssl_version) ...](https://docker-py.readthedocs.io/en/stable/change-log.html)

Someone on [Stack overflow](https://stackoverflow.com/questions/77641240/getting-docker-compose-typeerror-kwargs-from-env-got-an-unexpected-keyword-ar) mentioned that `sudo pip install --upgrade docker-py` fixed the issue. Worth a try?

**Comment by al-bear** [comment]
THX claesto!

Upgrade docker-py fixed the initial issue :-)

Unfortunately I now get the following error:
ImportError: cannot import name 'ContextAPI' from 'docker'

**Comment by claesto** [comment]
> Upgrade docker-py fixed the initial issue :-)

Is there a specific reason why you're using `docker-py`? I don't recall it's a necessary library that's needed to run docker? Also checking [docker-py history](https://pypi.org/project/docker-py/#history) it hasn't had a release since **2016**.

If you run Debian on the Pi I assume you can consider it _regular Debian_ and follow this guide: https://docs.docker.com/engine/install/debian/

If you run Raspberry Pi OS, which is Debian based if I remember (https://www.raspberrypi.com/software/), you can follow this guide https://pimylifeup.com/raspberry-pi-docker/ to setup Docker. I think it's the one I followed as well for my Pi setup.

Hope you can get it resolved!

**Comment by al-bear** [comment]
Thank you again claesto!

I didn't see the forest for the trees ;-)

I'm going to fix the basics now.
